spring:
  datasource:
    url: jdbc:mysql://8.130.183.113:3306/userCenter
    username: root
    password: hhh318413085066
    driver-class-name: com.mysql.cj.jdbc.Driver
  session:
    timeout: 86400
